name: Send Discord Message on PR Merge
on:
  pull_request:
    merged:

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Discord.js
        run: |
          yarn install

      - name: Send message
        run: |
          node send_message.js