name: Merge
on:
  pull_request:
    branches:
      - main
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge branch
        uses: actions/github-script@v3
        with:
          script: |
            echo "Merging branch into main..."
            node send_message.js