name: Pull request merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  telegram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          channelId: ${{ secrets.TELEGRAM_CHANNEL_ID }}
